[package]
name = "daedalus-kit"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "1.9.1"
byteorder = "1.5.0"
c2rust-bitfields = "0.18.0"
codespan-reporting = "0.11.1"
encoding_rs = "0.8.33"
logos = "0.14.0"
thiserror = "1.0.58"
