[package]
name = "dat"
version = "0.1.0"
edition = "2021"

[dependencies]
daedalus-bytecode.workspace = true

bstr.workspace = true
encoding_rs.workspace = true
bitflags.workspace = true
byteorder.workspace = true
num-derive.workspace = true
num-traits.workspace = true


pretty_assertions = "1"

