[package]
name = "daedalus-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
daedalus-lexer.workspace = true
logos.workspace = true
thiserror.workspace = true

[dev-dependencies]
indoc.workspace = true
