[package]
name = "daedalus-fmt"
version = "0.1.0"
edition = "2021"

[dependencies]
daedalus-parser.workspace = true
src-file.workspace = true
encoding_rs.workspace = true
codespan-reporting.workspace = true

[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
