name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: cargo build --workspace --target ${{ matrix.target }}
      - run: cargo test --workspace --target ${{ matrix.target }}
  
